### ISSUE TITLE
AMP homepage noindex

### ISSUE THREAD

**Issue by monicalf** [Yoast/yoastseo-amp#101]
### What did you expect to happen?
Hello, I’ve been using Yoast and AMP plugin (https://wordpress.org/plugins/accelerated-mobile-pages/) for while without any problems by now. But last week, I received an error message in Search Console. 

My AMP homepage is noindex. Is there a way to remove the meta robots from a specific URL? It seems to be a deeper problem than I can handle. I will appreciate any help. Thanks.

### Technical info
* WordPress version: 4.9.6
* Yoast SEO version: v7.7.1
* Yoast SEO Glue version: not using
* AMP plugin version: 0.9.97.1

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
