### ISSUE TITLE
[Feature Request] Update plugin to reflect possible amp changes

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#102]
Add /amp/ to the end of a url to see the AMP page makes pages go to 404.

It appears from this post: https://github.com/Automattic/amp-wp/issues/1270 AND this one https://wordpress.org/support/topic/0-6-0-not-working-for-pages/#post-9903766 that the adding `amp` is going to be or will be depreciated in favor of adding `?amp`. 

We may need to update the plugin and documentation accordingly.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/yoastseo-amp/issues/22

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
