### ISSUE TITLE
Classes that contain '>' are encoded with '&gt;' upon saving the CSS style in the field 'Extra CSS'

### ISSUE THREAD

**Issue by symonny** [Yoast/yoastseo-amp#105]
### What did you expect to happen?
preserve the character unencoded as '>' so that classes are properly recognized as style

### What happened instead?
  character '>' becomes '&gt;' and the classes don't work properly :/ 

### How can we reproduce this behavior?
1. Go to: https://website.com/wp-admin/admin.php?page=wpseo_amp#top#design
2. In field Extra CSS enter:
.thrv_wrapper.section-definition .section-definition-wrapper > .tve-cb {
  justify-content: center;
  display: flex;
  flex-direction: column;
} 

<img width="802" alt="screen shot 2018-10-16 at 13 26 25" src="https://user-images.githubusercontent.com/2889300/47045341-6f994900-d147-11e8-8c50-7a597ca98f06.png">

3. Save the changes by clicking the red button at the bottom of the page 
4. Refresh page and notice the save text:
Character '>' has been encoded as '&gt;' 

.thrv_wrapper.section-definition .section-definition-wrapper &gt; .tve-cb {
  justify-content: center;
  display: flex;
  flex-direction: column;
} 
 
<img width="806" alt="screen shot 2018-10-16 at 13 26 07" src="https://user-images.githubusercontent.com/2889300/47045357-758f2a00-d147-11e8-974c-0f12c68c7a68.png">

Please checkout https://www.studiobinder.com/blog/what-does-a-producer-do/amp/ 
to see the classes output as well:

<img width="2368" alt="screen shot 2018-10-16 at 13 35 33" src="https://user-images.githubusercontent.com/2889300/47045789-8a1ff200-d148-11e8-8072-6530b60bdcca.png">
 
### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: Yoast Premium  8.4 
* Yoast SEO Glue version: 0.4.3
* AMP plugin version: 0.7.2

**Comment by symonny** [comment]
Temporary solved by making the following chnages in the plugin glue-for-yoast-seo-amp

1. /wp-content/plugins/glue-for-yoast-seo-amp/classes/class-options.php 
in method **sanitize_options** comment line:

//$safe_text = _wp_specialchars( $safe_text, ENT_NOQUOTES );

<img width="824" alt="screen shot 2018-10-16 at 14 27 16" src="https://user-images.githubusercontent.com/2889300/47048681-fa7e4180-d14f-11e8-8d62-60d8bec60b45.png">

2. /wp-content/plugins/glue-for-yoast-seo-amp/classes/class-frontend.php 
in method **sanitize_options** comment line:

//$extra_css            = _wp_specialchars( $extra_css, ENT_NOQUOTES );

<img width="974" alt="screen shot 2018-10-16 at 14 27 01" src="https://user-images.githubusercontent.com/2889300/47048686-fe11c880-d14f-11e8-8883-150dd2e487d9.png">

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
