### ISSUE TITLE
[Enhancement] When a user enters a Default Image if image is too small or large output notification letting user aware 

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#110]
### What did you expect to happen?

An alert if image is wrong size

### What happened instead?

No Alert

1. Add an image into the Default Image section in Glue for AMP plugin

<img width="731" alt="screen shot 2019-01-15 at 4 36 50 pm" src="https://user-images.githubusercontent.com/8238074/51211532-cef02c00-18e3-11e9-8b3d-11aee3a14e8a.png">

2.See that it gets outputted as an Imageobject but it is too small

<img width="1240" alt="screen shot 2019-01-15 at 4 36 41 pm" src="https://user-images.githubusercontent.com/8238074/51211544-d8799400-18e3-11e9-91fe-89455fb52c20.png">

3. We should show an alert if image is wrong size

Google explains ImageObject size here: https://developers.google.com/search/docs/data-types/article#logo-guidelines.

### Technical info
* WordPress version: 503
* Yoast SEO version: 9.4.1
* Yoast SEO Glue version: 0.4.3
* AMP plugin version: 1.0.1

**Comment by priscillamc** [comment]
FYI, There's also an open issue to do the same thing in the AMP repo: https://github.com/ampproject/amp-wp/issues/1812

**Comment by priscillamc** [comment]
Please inform the customer of conversation # 464345  when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
