### ISSUE TITLE
[Feature Request] Detect if AMP is installed and if not output a notification letting users know they need to install AMP

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#111]
If a user has the Glue plugin installed it does not appear in the SEO section.

<img width="569" alt="screen shot 2019-01-16 at 12 35 08 pm" src="https://user-images.githubusercontent.com/8238074/51267179-2c8b8380-198b-11e9-800f-b03241b3eebe.png">

We should detect if AMP is installed and if not output a notification in the SEO-General section letting users know they need to install AMP.

This would improve the UX

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
