### ISSUE TITLE
[Feature Request] Change the Width for the AMP Default Image to conform with Google's Standards for AMP Images

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#117]
**We state that the image must be 696px wide:**

<img width="736" alt="Screen Shot 2019-03-27 at 2 34 41 PM" src="https://user-images.githubusercontent.com/8238074/55102756-7edcd500-509d-11e9-9e55-42f584f70198.png">

**Google says here: https://developers.google.com/search/docs/data-types/article it must be 1200px**

<img width="886" alt="Screen Shot 2019-03-27 at 2 35 13 PM" src="https://user-images.githubusercontent.com/8238074/55102783-8e5c1e00-509d-11e9-8ba5-974a1841b10c.png">

**We should change the width so it reflects what Google's requirements are. This will help improve UX and Technical SEO**

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
