### ISSUE TITLE
Fix AMP build on trunk

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoastseo-amp#119]

**Comment by Xyfi** [comment]
Fixed in https://github.com/Yoast/yoast-acf-analysis/commit/75d4fac542452e5b7505159d8809b34a0d61cc38

**Comment by Xyfi** [comment]
Fixed in https://github.com/Yoast/yoastseo-amp/commit/cec0ffa3d727ef55672edc5cfe295e68b8f29d39.
