### ISSUE TITLE
[Feature Request] Provide ability to support AMP Stories

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#121]
## Is your feature request related to a problem? Please describe.

Users want to support AMP stories. AMP Stories are a way to improve engagement as described here https://developers.googleblog.com/2018/02/amp-stories-bringing-visual.html

## Describe the solution you'd like

Provide ability to support AMP Stories. We may need to add support for its elements: https://amp.dev/documentation/components/amp-story?referrer=ampproject.org

## why you think the feature request is something we should consider for the Yoast SEO plugins?

Since the world is moving towards a mobile first, anything we can do to help users compete in mobile is something we should do. 

## Who would benefit?

Users who have AMP and want to improve UX and Technical SEO.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 510845 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
