### ISSUE TITLE
Verify use of "wpseo_sitemaps_supported_post_types" hook

### ISSUE THREAD

**Issue by jrfnl** [Yoast/yoastseo-amp#124]
This plugin has a function call applying the `wpseo_sitemaps_supported_post_types` filter.

https://github.com/Yoast/yoastseo-amp/blob/1de0561adca9830ffbe58f2be3df7abeb5ee5670/classes/views/admin-page.php#L35-L36

However a search of the YoastSEO Free/premium does not yield any results for this filter.

It needs to be determined:
1. If this is a YoastSEO Free/Premium filter which was deprecated/removed/replaced.
    - If the filter was removed from Free/Premium, it should probably also be removed from the AMP plugin.
    - If the filter was deprecated/replaced, the use of it in the AMP plugin should probably also be deprecated/replaced.
2. If this is not a filter which comes from YoastSEO Free/Premium, where does it come from ?
3. If this is a AMP plugin native filter, it should be deprecated and replaced with a filter using the correct plugin prefix.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
