### ISSUE TITLE
Use Wordpress-SEO's new surfaces

### ISSUE THREAD

**Issue by andizer** [Yoast/yoastseo-amp#134]
With the surfaces (https://github.com/Yoast/wordpress-seo/pull/14093) in mind we should replace some code in `classes/frontend.php` 

For example we have to replace `WPSEO_Frontend::get_instance()->canonical( false );` by the one defined in the surface `YoastSEO()->current_page->get_canonical()`

We also have to find a solution to handle:
- `$GLOBALS['wpseo_og'] = new WPSEO_OpenGraph();`
- `WPSEO_Twitter::get_instance();`

To do:
- [ ] Start by writing test 
- [ ] Search for `WPSEO_Frontend`, `WPSEO_Twitter`, `WPSEO_OpenGraph`
- [ ] Replace WPSEO_Frontend::get_instance()
- [ ] Replace `$GLOBALS['wpseo_og'] = new WPSEO_OpenGraph();`
- [ ] Replace `WPSEO_Twitter::get_instance();`

**Comment by lkraav** [comment]
@andizer how's this coming along? Glue plugin is spamming debug logs like crazy. I'm wondering if I should just disable it for now.

**Comment by andizer** [comment]
This issue isn't needed anymore. The functionality has been moved to the SEO plugin itself. 

https://github.com/Yoast/yoastseo-amp/issues/141
