### ISSUE TITLE
Glue for Yoast SEO & AMP plugin removes rel="noopener" attributes from all links on AMP pages

### ISSUE THREAD

**Issue by arpitnext** [Yoast/yoastseo-amp#138]
### What did you expect to happen?

[rel="noopener"](https://developers.google.com/web/tools/lighthouse/audits/noopener) is highly recommended, as it prevents the new pages from being able to access the window.opener property and ensures it runs in a separate process.

### What happened instead?

The "Glue for Yoast SEO & AMP" plugin removes rel="noopener" attributes from all links on AMP pages.

### How can we reproduce this behavior?

Install the Glue plugin, and enable the AMP pages on any WordPress installation. Create a post or page, and insert a hyperlink in its content with  rel="noopener" attribute. For example, 

`<a href="https://www.example.com"  rel="noopener">Sample Link</a>`

Visit the AMP URL of the above post, and check the hyperlink using browser's devtools. 
 rel="noopener" will be stripped out. Disable the Glue plugin, and check again. This time, the  rel="noopener" attribute will be there.

### Investigation

On further investigation, I found that the following code in the `glue-for-yoast-seo-amp/classes/blacklist-sanitizer.php` file is responsible for the above behaviour: 

(Starting @ line # 103)
```
/**
	 * Sanitizes anchor attributes.
	 *
	 * @param DOMNode $node      The DOM node to sanitize the passed attribute from.
	 * @param DOMNode $attribute The attribute to sanitize.
	 *
	 * @return void
	 */
	private function sanitize_a_attribute( $node, $attribute ) {
		$attribute_name = strtolower( $attribute->name );

		if ( $attribute_name === 'rel' && $attribute->value !== 'nofollow') {
			$node->removeAttribute( $attribute_name );
		}
	}
```

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
