### ISSUE TITLE
Deprecated function errors after upgrading Yoast SEO to 14.1

### ISSUE THREAD

**Issue by qsricardosevero** [Yoast/yoastseo-amp#139]
* [X] I've read and understood the [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md).

* [X] I've searched for any related issues and avoided creating a duplicate issue.

### How can we reproduce this behavior?

1. As I told here: https://wordpress.org/support/topic/wpseo_frontend-obsolet-3/#post-12823261 You just need to enter at our blog in any /AMP article.Use this for example: https://blog.quantosobra.com.br/dicas-para-vender-mais-durante-a-pandemia-de-coronavirus/amp/

2. You'll see this errors:

3. Deprecated: WPSEO_Frontend::canonical está obsoleto desde a versão WPSEO 14.0 sem nenhuma alternativa disponível. in /var/www/html/wp-includes/functions.php on line 4723

Deprecated: WPSEO_Twitter::get_instance está obsoleto desde a versão WPSEO 14.0 sem nenhuma alternativa disponível. in /var/www/html/wp-includes/functions.php on line 4723

Deprecated: WPSEO_OpenGraph::__construct está obsoleto desde a versão WPSEO 14.0 sem nenhuma alternativa disponível. in /var/www/html/wp-includes/functions.php on line 4723

After disabling Glue for Yoast SEO & AMP the errors disapeared.

### Technical info

* WordPress version: 5.4.1

* Yoast SEO version: 14.1

* If relevant, which editor is affected (or editors): 

- [x] Classic Editor

- [ ] Gutenberg

- [ ] Classic Editor plugin

* Which browser is affected (or browsers): 

- [x] IE11

- [x] Edge

- [x] Chrome

- [x] Firefox

- [x] Safari

* Relevant plugins in case of a bug:

Glue for Yoast SEO & AMP 0.6

* Tested with theme:

Jevelin 4.6.8

**Comment by lkraav** [comment]
You beat me to filing this issue by 30 seconds :+1: 

Probably related https://github.com/Yoast/yoastseo-amp/issues/134

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
