### ISSUE TITLE
Prepare for final release / sunset

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoastseo-amp#141]
We're going to sunset this plugin, because all functionality has been moved to Yoast SEO. The final release should contain only the following files:
- [x] yoastseo-amp.php containing the plugin PHP header and a notification encouraging users to uninstall the plugin. 
- [x] readme.txt explaining that the plugin is not needed anymore.
- [ ] Ping me when this has been merged so we can plan a release date.

@jdevalk will provide the copy

**Comment by jdevalk** [comment]
The copy for both the changelog, the readme.txt "main copy" _and_ the notification:

> The Yoast SEO AMP plugin is no longer needed. Through good collaboration with Google the functionality of this plugin is now part of both Yoast SEO and the official AMP plugin. If you still have this plugin running we’d suggest updating both the Yoast SEO and AMP plugin and removing the glue plugin.

@westonruter any feedback from the Google side of things on this?

**Comment by afercia** [comment]
@IreneStr I guess the 0.6 branch should be merged into trunk?
Trunk appears to be 0.5.

**Comment by afercia** [comment]
@jdevalk on which pages do we want to show the notice? (I'm assuming it's a WP admin notice)

For now, I was thinking at 'plugins.php', 'plugin-install.php', 'update-core.php'.

Also, I'd make the notice of type "info" i.e. with the blue border, example:

<img width="1278" alt="Screenshot 2020-05-19 at 11 45 47" src="https://user-images.githubusercontent.com/1682452/82311685-56f9b080-99c6-11ea-91a1-a8f6c06d2f71.png">

**Comment by IreneStr** [comment]
@afercia I've discussed the above with @thijsdevalk  and he agrees with your choices :)

**Comment by westonruter** [comment]
> any feedback from the Google side of things on this?

Looks great!

**Comment by amedina** [comment]
Great indeed!
