### ISSUE TITLE
AMP Plugin Custom Code Overwritten

### ISSUE THREAD

**Issue by ghost** [Yoast/yoastseo-amp#19]
### What did you expect to happen?

In shcema.org post type should be NewsArticle as per AMP plugin custom code:

schema.org","@type":"NewsArticle"

This is coming from the following custom code:

`add_filter( 'amp_post_template_metadata', 'xyz_amp_modify_json_metadata', 10, 2 );

function xyz_amp_modify_json_metadata( $metadata, $post ) {
    $metadata['@type'] = 'NewsArticle';

```
$metadata['publisher']['logo'] = array(
    '@type' => 'ImageObject',
    'url' => get_template_directory_uri() . '/images/logo.jpg',
    'height' => 60,
    'width' => 240,
);

return $metadata;
```

}`
### What happened instead?

post type is just 'Article'
### How can we reproduce this behavior?

Use the above custom code to change the post type from default BlogPost to NewsArticle and then use the Glue Plugin and see the result.
### Technical info
- WordPress version:4.4.2
- Yoast SEO version:3.1.1
- Yoast SEO Glue version:0.3.2
- AMP plugin version:0.3.2

**Comment by OPPtester** [comment]
As a temp. fix, I edited the class-frontend.php file and changed 'Article" to 'NewsArticle'

`private function get_post_schema_type( $post ) {
			if ( 'post' === $post->post_type ) {
				$type = 'NewsArticle';`

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
