### ISSUE TITLE
Can't filter posts in admin panel after enabling plugin

### ISSUE THREAD

**Issue by laserjobs** [Yoast/yoastseo-amp#2]
If you go to All Posts (/wp-admin/edit.php) and try to filter it returns to the homepage of the site with the plugin enabled. If the plugin is disabled filter works again.

**Comment by laserjobs** [comment]
Tried it on two other sites that are similar and did not have the issue. Will look into it further.

**Comment by jdevalk** [comment]
Can't reproduce, sorry, I think it's another plugin?

**Comment by laserjobs** [comment]
It is very strange behavior that I thought had to do with a redirect plugin but even with those disabled the same thing happens. It is only once I enable the yoast-seo AMP plugin does it happen, if I disable it works again. Any advice on how to troubleshoot this issue?

**Comment by laserjobs** [comment]
Works now with the Update of this plugin and Yoast Seo
