### ISSUE TITLE
Featured Images not showing

### ISSUE THREAD

**Issue by TR-DK** [Yoast/yoastseo-amp#20]
After upgrade to:
Glue for Yoast SEO & AMP - Version 0.3.2
Yoast SEO Premium - Version 3.1.2
WP Version 4.4.2

featured images are not showing up anymore. 

http://www.torbenrick.eu/blog/change-management/iceberg-that-sinks-organizational-change/amp/

When using PageFroge the featured images shows up on AMP.

**Comment by kelleeg** [comment]
With the update of Yoast 3.1.2, our wp-admin editor will not work, nor will the images show in the image gallery.  Turning off Yoast Premium plugin makes this problem go away.  What gives?

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
