### ISSUE TITLE
VM331:3 Uncaught SyntaxError: Unexpected token }(…)    VM331:3

### ISSUE THREAD

**Issue by marky07** [Yoast/yoastseo-amp#21]
### What did you expect to happen?

See the AMP validation successful message upon testing my latest post in the development mode for AMP. The error message appears on all posts that I test.
### What happened instead?

error message as follows

---

VM331:3 Uncaught SyntaxError: Unexpected token }(…)    VM331:3

InjectedScript._evaluateOn  @   VM253:878
InjectedScript._evaluateAndWrap @   VM253:811
InjectedScript.evaluate @   VM253:667

---

When typing in a post followed by /amp it seems to appear fine though?
### Technical info
- WordPress version: 4.4.2
- Yoast SEO version: 3.1.2
- Yoast SEO Glue version: 0.3.2
- AMP plugin version: 0.3.2

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
