### ISSUE TITLE
AMP for pages not working

### ISSUE THREAD

**Issue by rvencu** [Yoast/yoastseo-amp#22]
### Technical info
- WordPress version: 4.4.2
- Yoast SEO Premium version: 3.1.3
- Yoast SEO Glue version: 0.3.2
- AMP plugin version: 0.3.2

**Comment by rvencu** [comment]
the recent version of the first plugin suggested (facebook instant articles, amp, etc) was able to enable page post type amp support. being based only on amp plugin or amp plus yoast glue there is only 404 error for any page with /amp in the end

**Comment by idarek** [comment]
Hello,
Is there any news on AMP for pages issue?

I noticed that adding ?amp=1 is working for pages, but not /amp/

https://www.andrewsfasteners.uk/ce/?amp=1

https://www.andrewsfasteners.uk/ce/amp/

**Comment by digitalcolony** [comment]
I'm experiencing the same result as idarek. 

?amp=1   works, however /amp/ does not.

**Comment by Pcosta88** [comment]
AMP for pages may no longer work. It appears to be depreciated in favor of 

`?amp
`
Related: https://wordpress.org/support/topic/0-6-0-not-working-for-pages/#post-9903766 and https://github.com/Automattic/amp-wp/issues/1270

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
