### ISSUE TITLE
404 error only when used with static front page

### ISSUE THREAD

**Issue by Hans-Jung** [Yoast/yoastseo-amp#24]
When using the plugin in combination with a static front page in WordPress, the /amp-pages are not working. For the front page, WP is asking to write the first post, for the other pages it is returning a 404 response.

Working:
https://example.com/some-page/?amp=1
https://example.com/someotherpage/?amp=1

Not working (404):
https://example.com/amp
https://example.com/some-page/amp
https://example.com/someotherpage/amp

Not working (empty page):
https://example.com/?amp=1

It appears to be the same error that was posted in the support-forum over at wordpress.org:
https://wordpress.org/support/topic/bug-static-front-page-404
### Technical info
- WordPress version: 4.2.2
- Yoast SEO version: 3.1.2
- Yoast SEO Glue version: 0.3.2
- AMP plugin version: 0.3.2

**Comment by monbauza** [comment]
Please inform the customer of conversation # 132822 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
