### ISSUE TITLE
CUSTOM_JAVASCRIPT_DISALLOWED

### ISSUE THREAD

**Issue by marcobee** [Yoast/yoastseo-amp#25]
### What did you expect to happen?

I think that de Glue for Yoast SEO-AMP automaticly makes the amp page (post's). 
### What happened instead?

I'm getting more and more warnings from the google search console about the java scrips on the post's and cant fix this becase the AMP posts are automaticly made by the plugins. (I think these are the java scrips are from google adsence program, but i might be wrong).
### How can we reproduce this behavior?

Do not show the scripts in the AMP posts/directory would be an option, but in this case the webmasters will no more receive adsence income with the google ads with these AMP types of pages/post(s) when this will be more used by the users in the future...
### Technical info
- WordPress version: 4.5.2
- Yoast SEO version: 3.2.5 
- Yoast SEO Glue version: 0.3.2
- AMP plugin version: 0.3.2

**Comment by marcobee** [comment]
Dear friendly helpdesk, Is there any solution yet?
![screenshot-amp-30-5-2016](https://cloud.githubusercontent.com/assets/19528193/15673299/0b255a9e-2736-11e6-9353-a5be97ab83ea.jpg)

**Comment by csarigoz** [comment]
Hi there @marcobee 

Did you add Google Analytics tracking code via the plugin? That might be the cause of the problem. I opened [this issue](https://github.com/Yoast/yoastseo-amp/issues/29) with necessary details about the Google Analytics tracking code causing this error. I hope the Yoast Team could find a solution.

Or it might be another JavaScript injection from `Extra code in <head>` textbox in `Design` section of the plugin.

**Comment by marcobee** [comment]
thx

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
