### ISSUE TITLE
 Redirect ugly URL's to clean permalinks results in AMP posts/pages being redirected

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#26]
### What did you expect to happen?

When "redirect" is selected under the setting _SEO->Advanced->Permalinks->Redirect ugly URL's to clean permalinks_ it would not redirect the AMP part of a post/page
### What happened instead?

When "redirect" is selected it results on the AMP post/page being redirect to the non-AMP post/page.
### How can we reproduce this behavior?

1.Install and activate the plugins: AMP, Yoast SEO, and Glue for Yoast SEO & AMP
2.Create and publish a post

![amp test](https://cloud.githubusercontent.com/assets/8238074/15575712/472b5fe2-2322-11e6-9e66-1a184e0e50c3.jpg)

3.Select "redirect" and save.
![screen shot 2016-05-26 at 9 14 49 am](https://cloud.githubusercontent.com/assets/8238074/15575722/537b39f2-2322-11e6-8229-c723190420c3.png)

4.See that AMP has been redirected to the non-AMP post.

![redirect amp](https://cloud.githubusercontent.com/assets/8238074/15575805/c089d7b0-2322-11e6-8d24-a85e517640d5.jpg)
### Technical info
- WordPress version: 4.5.2
- Yoast SEO version: 3.2.5
- Yoast SEO Glue version: 0.3.2
- AMP plugin version: 0.3.2

**Comment by amboutwe** [comment]
This happens with only Yoast SEO and the AMP plugin. However, a user could expect the glue plugin to prevent the issue.

**Comment by AskKim** [comment]
Please inform the customer of conversation # 120625 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
