### ISSUE TITLE
Meta Descriptions not displaying on AMP pages

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#27]
### What did you expect to happen?

1. Yoast SEO pulls meta data such as open-graph, article twitter tags, and some JSON+LD. I would then expect the meta description to be viewable with the AMP plugin we recommend in this post: https://yoast.com/setting-up-wordpress-for-amp-accelerated-mobile-pages/.

### What happened instead?

The meta description is added into a twitter and open-graph descriptions. However, there is no meta description tag. 

### How can we reproduce this behavior?

**1.Install AMP and Glue**

**2.Create a post**

**3.Add a meta description**

**4.View in AMP**

**Meta Description Add on Post in Backend**

![meta](https://cloud.githubusercontent.com/assets/8238074/17567502/a23b3a98-5f0d-11e6-8205-8db2b1ca30c3.jpg)

**View Meta Description Tag as a Post**

![regular post](https://cloud.githubusercontent.com/assets/8238074/17567538/c7efd776-5f0d-11e6-8002-c8a7ffdab075.jpg)

**View Post as AMP. See that Meta Description does not appear**

![nometa](https://cloud.githubusercontent.com/assets/8238074/17567617/203a767a-5f0e-11e6-8ae8-b8e1534694fa.jpg)
### Technical info
- WordPress version: 4.5.3 (also on 4.9.5)
- Yoast SEO version: 3.4.2 (also on 7.3)
- Yoast SEO Glue version: 0.3.2 (also on 0.4.2)
- AMP plugin version: 0.3.2 (also on 0.6.2): https://wordpress.org/plugins/amp/

**NOTE 1:** 
The [AMP plugin ](https://wordpress.org/plugins/amp/)above  which we suggest is a "good" one [here](https://yoast.com/setting-up-wordpress-for-amp-accelerated-mobile-pages/) does not offer any relevant settings other than outputting AMP on posts and pages. See below for settings

![screen shot 2018-04-18 at 11 35 59 am](https://user-images.githubusercontent.com/8238074/38942443-c6e5eda0-42fc-11e8-93a6-34d57778d827.png)

**NOTE 2:**
Users may be able to output the meta description using a different AMP plugin such as https://wordpress.org/plugins/accelerated-mobile-pages/. This plugin appears to have a feature in the Settings-SEO to toggle Yoast's meta descriptions and make them appear on an AMP page.

<img width="1073" alt="screen shot 2018-12-24 at 9 34 11 am" src="https://user-images.githubusercontent.com/8238074/50401840-a56a3780-075f-11e9-908c-837018261b87.png">

Tested with v0.9.97.23

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 140828 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 149823 when this conversation has been closed.

**Comment by vijayp4you** [comment]
Hi i am also facing same issue. In semrush i got 10k pages doNot have meta description due to this.
Any temparay solution plz.

**Comment by shendison** [comment]
Been two months now... Still no fix?

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 154340 when this conversation has been closed.

**Comment by jamogon** [comment]
Any idea how to fix this?

I created a temporary solution, but is not a good solution. I write this to solve it:

In file: amp/includes/amp-post-template-actions.php

```
add_action( 'amp_post_template_head', 'amp_post_template_add_meta_description' );
function amp_post_template_add_meta_description( $amp_template ) {
?>
        <meta name="description" content="<?php echo esc_html( $amp_template->get('metadata')['description'] ); ?>" />
	<?php
}
```

**Comment by monbauza** [comment]
Please inform the customer of conversation # 207310 when this conversation has been closed.

**Comment by jayze09** [comment]
There's an option in AMP plugin that you can enable the meta description to carry over from YOAST.

**Comment by jayze09** [comment]
![yoast-desc](https://user-images.githubusercontent.com/7261902/36292496-f426dd38-131d-11e8-902b-f2c7c75e73dc.JPG)

Here's a screen shot from AMP plugin General Settings > SEO

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 347393 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 402802 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 457398 when this conversation has been closed.

**Comment by abdobasha2004** [comment]
> add_action( 'amp_post_template_head', 'amp_post_template_add_meta_description' );
> function amp_post_template_add_meta_description( $amp_template ) {
> ?>
>         <meta name="description" content="<?php echo esc_html( $amp_template->get('metadata')['description'] ); ?>" />
> 	<?php
> }

it is a good idea, but not working now, knowing that no amp-template-actions.php file nowadays!

**Comment by icaksama** [comment]
Add this code in your functions.php:

```
// ADD META DESCRIPTION IN AMP PAGE
add_action( 'amp_post_template_head', 'add_meta_description' );
function add_meta_description() {
   if(function_exists( 'is_amp_endpoint' ) && is_amp_endpoint()) {
        $meta_description = get_post_meta(get_the_ID(), '_yoast_wpseo_metadesc', true);
        echo '<meta name="description" content="' . $meta_description . '">';
   }
}
```

**Comment by mihdan** [comment]
```
<?php
add_action(
	'amp_post_template_head',
	function ( $amp_template ) {
		if ( ! class_exists( 'WPSEO_Frontend' ) ) {
			return;
		}
		$wpseo = WPSEO_Frontend::get_instance();
		?>
		<meta name="description" content="<?php echo esc_html( $wpseo->metadesc( false ) ); ?>" />
		<?php
	}
);
```

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
