### ISSUE TITLE
Plugin activation show one validation error

### ISSUE THREAD

**Issue by karanbhagat95** [Yoast/yoastseo-amp#28]
### What did you expect to happen?

AMP by automattic and glue showed a problem with clouflare rocket launcher and uninstalling this plugin removed many errors.
### What happened instead?

Now there is only one problem, with Glue Yoast deactivated the AMPs shows no validation errors but when I enable it then it shows one error and that is " The tag 'script' is disallowed except in specific forms. CUSTOM_JAVASCRIPT_DISALLOWED line 92, column 0"
### How can we reproduce this behavior?

Can this error be solved to show perfect AMP version.
### Technical info
- WordPress version:
- Yoast SEO version: 4.5.3
- Yoast SEO Glue version: 0.3.2
- AMP plugin version: 0.3.2

The website can be viewed here http://www.focusandleap.com/

**Comment by csarigoz** [comment]
Hi there @karanbhagat95 

Did you add Google Analytics tracking code via the plugin? That might be the cause of the problem. I opened [this issue](https://github.com/Yoast/yoastseo-amp/issues/29) with necessary details about the Google Analytics tracking code causing this error. I hope the Yoast Team could find a solution.

Or it might be another JavaScript injection from `Extra code in <head>` textbox in `Design` section of the plugin.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
