### ISSUE TITLE
Google Analytics Tracking Code Causes Error on the AMP Validator [CUSTOM_JAVASCRIPT_DISALLOWED]

### ISSUE THREAD

**Issue by csarigoz** [Yoast/yoastseo-amp#29]
### What did you expect to happen?

I was expecting Google Analytics tracking code to function properly. 
I think instead of adding the JavaScript tracking code directly to HTML source code, you'd need to tweak the tracking code into the analytics code format that is explained [here](https://github.com/Automattic/amp-wp/blob/master/readme.md#analytics).
### What happened instead?

I received this error on the AMP Validator: `The tag 'script' is disallowed except in specific forms. [CUSTOM_JAVASCRIPT_DISALLOWED]`

You can find the screenshot of the error I had [here](https://www.evernote.com/l/AVSo5q0ClQdI7atJgCrh6zK_TR8sMuVEFS8).

I've found other people experiencing the same problem as well. Here are some links:
https://wordpress.org/support/topic/the-tag-script-is-disallowed-except-in-specific-forms/
https://wordpress.org/support/topic/error-script-with-google-search-console/#post-7202538
https://wordpress.org/support/topic/amp-validation-error-when-using-amp-analytics/
### How can we reproduce this behavior?
1. Adding a Google Analytics Tracking Code (the js script taken from the Google Analytics interface) to _AMP - Yoast SEO -> Analytics_ code textbox.
2. Trying to validate an AMP page on [The AMP Validator](https://validator.ampproject.org/)
### Technical info
- WordPress version: 4.6
- Yoast SEO version: 3.4.2
- Yoast SEO Glue version: 0.3.2
- AMP plugin version: 0.3.3

**Comment by rentageekmom** [comment]
+1 on this. This was also seen on our site and fixed by removing the 'optional' tracking code in the  AMP - Yoast SEO -> Analytics code textbox.

**Comment by Pcosta88** [comment]
related? https://github.com/Yoast/yoastseo-amp/issues/40

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
