### ISSUE TITLE
Migrate the visual AMP setting to the WordPress Customizer

### ISSUE THREAD

**Issue by ataylorme** [Yoast/yoastseo-amp#30]
### What did you expect to happen?

As a WordPress user I expect to be able to preview changes to a post.
### What happened instead?

There is no preview for AMP settings. I had to update settings in the WordPress dashboard, save the settings, then reload the front-end of the site. Without being able to see how settings effect the front-end of the site this is a frustrating experience.
### How can we reproduce this behavior?

Login to the WordPress dashboard and edit AMP settings in the _Design_ tab.
### Technical info
- WordPress version: `4.6.1`
- Yoast SEO version: `3.5`
- Yoast SEO Glue version: `0.3.2`
- AMP plugin version: `0.3.3`

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
