### ISSUE TITLE
<LEAD> tags not stripped for AMP posts

### ISSUE THREAD

**Issue by imfinlay** [Yoast/yoastseo-amp#35]
For some posts I use a <LEAD> tag, which creates an AMP error "The tag 'lead' is disallowed." This needs to be stripped, or converted to another suitable tag. At the moment it isn't.

It seems I can reproduce just by adding a LEAD tag to any post.
### Technical info
- WordPress version: WP4.6.1
- Yoast SEO version: 3.6.1
- Yoast SEO Glue version: 0.3.3
- AMP plugin version: 0.3.3

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
