### ISSUE TITLE
Adding boxes for custom Head and Footer feature request

### ISSUE THREAD

**Issue by laserjobs** [Yoast/yoastseo-amp#36]
Could I suggest a feature to add a custom Head and Footer box for things like Amp-ads can be simply added to the AMP output?

https://github.com/automattic/amp-wp#head-and-footer
https://www.ampproject.org/docs/reference/components/amp-ad

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
