### ISSUE TITLE
Plugin Title

### ISSUE THREAD

**Issue by bhubbard** [Yoast/yoastseo-amp#37]
It would be nice if this plugin can have consistent naming with the other plugins.

Yoast SEO: Local
Yoast SEO: Video
Yoast SEO: News
Yoast SEO: Amp

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
