### ISSUE TITLE
Custom Design option in the official AMP plugin

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoastseo-amp#38]
Sounds like we need to remove our design options and see if we can migrate the current settings into the AMP provided design option.

A version check would be required for the smoothest transition.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
