### ISSUE TITLE
In the "Extra CSS" field the child combinator ">" is replaced by its HTML entity "&gt;" when saving, thus the rule does not work

### ISSUE THREAD

**Issue by diegocanal** [Yoast/yoastseo-amp#39]
### What did you expect to happen?

When saving changes, the child combinator "**>**" should be left as it is in order the CSS rule to work properly.
### What happened instead?

When saving changes, the child combinator "**>**" is replaced by its corresponding HTML entity "**`&gt;`**" , because of that the CSS rule does not work.
### How can we reproduce this behavior?

For instance, just paste the following code and save changes, immediately you will notice that the symbol is changed:
`.amp-wp-article-content li > ul, .amp-wp-article-content li > ol {
    padding-left: 1em;
}`
### Technical info
- WordPress version: 4.6.1
- Yoast SEO version: 3.7.0
- Yoast SEO Glue version: 0.3.3
- AMP plugin version: 0.4.2

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
