### ISSUE TITLE
Default image and analytics code do not work

### ISSUE THREAD

**Issue by patchlog** [Yoast/yoastseo-amp#40]
### What did you expect to happen?

See a default image for posts that don't have it. 
See the google analytics code in the posts.
### What happened instead?

Nothing. It looks like the analytics code is not even saved and the default image is not displayed on amp posts
### How can we reproduce this behavior?

Set a default image and analytics code and look at the amp version of the post.
### Technical info
- WordPress version: 4.6.1
- Yoast SEO version: 3.7.0
- Yoast SEO Glue version: 0.3.3
- AMP plugin version: 0.4.2

**Comment by Pcosta88** [comment]
WP: 4.6.1
Yoast: 3.9
AMP: 0.4.2
Glue: 0.3.3

![1](https://cloud.githubusercontent.com/assets/8238074/20797283/18ef11b2-b7a8-11e6-98fe-88bc66ea58d5.png)

![2](https://cloud.githubusercontent.com/assets/8238074/20797286/1bcb53f0-b7a8-11e6-9777-fbe9774a1c70.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 159189 when this conversation has been closed.

**Comment by brianlarson** [comment]
Having the same issue here. Using Yoast SEO Premium but I assume that has nothing to do with the issue?

**Comment by arcivanov** [comment]
Having the same issue.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 179233 when this conversation has been closed.

**Comment by TomCanning83** [comment]
I'm having the same issue with AMP.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 181169 when this conversation has been closed.

**Comment by TomCanning83** [comment]
Is there an actual fix for this? I've just tried adding analytics again and it's not working.

**Comment by Shyzer** [comment]
My issue is the exact same as described by mihaisecasiu and Pcosta88. Within the AMP - Yoast SEO plugin, nothing will save in the Analytics tab. When I paste my analytics code in the textarea then hit save, the page reloads with a "settings saved" message, yet the textarea is completely empty.

I’ve tested my AMP pages in development mode and receive the “AMP validation successful” message. My AMP pages also Google’s AMP Test tool with all greens.

* WordPress version: 4.7.4
* Yoast SEO Premium version: 4.7.1
* Yoast SEO Glue version: 0.4.2
* AMP plugin version: 0.4.2

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 206128 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 215709 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 226859 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 242165 when this conversation has been closed.

**Comment by brandimykle** [comment]
I am having the same issue and have informed customer service. They sent me to this page. Thanks!

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 250127 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/yoastseo-amp/issues/29

**Comment by iamazik** [comment]
Please inform the customer of conversation # 275818 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 299675 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 398911when this conversation has been closed.

**Comment by maybellyne** [comment]
Please inform the customer of conversation # 403139 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 451620 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 485816 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
