### ISSUE TITLE
When a page is being redirected the /amp/ is not respected

### ISSUE THREAD

**Issue by uprise10** [Yoast/yoastseo-amp#41]
### What did you expect to happen and What happened instead??

When a page is redirected (by WordPress itself, or Yoast Premium), the AMP version of that URL is being redirected to the regular URL and not the AMP version of the target URL.
### How can we reproduce this behaviour?

Change the slug or category of a post, so that WordPress automatically redirects the page, or create a redirect in Yoast SEO premium. Go the the /amp/ version of the old URL.
### Technical info
- WordPress version: 4.6.1
- Yoast SEO version: 3.7.2 (premium)
- Yoast SEO Glue version: 0.3.3
- AMP plugin version: 0.4.2

**Comment by derekseymour** [comment]
We're seeing the same thing in Glue for Yoast SEO & AMP (v0.3.3) when stopwords are automatically being removed from urls by the Yoast SEO plugin (v4.0.0) under Advanced -> Permalinks.  The indexed /amp/ urls without stopwords are being redirected to the non-AMP urls with stopwords.

### Example:
**Indexed AMP URL without stopwords:**
/2016/10/trial-points-benefits-personalized-medicine-mesothelioma-cancer-patients-13414/amp/
**301 redirects to non-AMP URL with stopwords:**
/2016/10/trial-points-to-benefits-of-personalized-medicine-for-mesothelioma-and-all-cancer-patients-13414/

![image](https://cloud.githubusercontent.com/assets/6097142/21184300/d81f7ca8-c1d9-11e6-8ba6-d8dca83e2e5f.png)

**Comment by pixelmac** [comment]
I experience the same.
So basically, we can't use AMP right now using Glue for Yoast SEO & AMP, right?

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
