### ISSUE TITLE
Removing additional css 

### ISSUE THREAD

**Issue by Sysix** [Yoast/yoastseo-amp#43]
### What did you expect to happen?
That I'm able to remove the additional styles via `remove_action`. Maybe Add a optional Checkbox or do not use objects-method call for `add_action`. Better is a static Method or a single function.

### What happened instead?
The Action has a random name, which is difficult to delete. Example: `0000000016aea4b7000000004e4bd6c9additional_css`
### How can we reproduce this behavior?
Try to delete the Action with remove_action

### Technical info
* WordPress version: 4.7-beta2
* Yoast SEO version: 3.7.1
 * Yoast SEO Glue version: 0.3.3
* AMP plugin version: 0.4.2

**Comment by barbub** [comment]
I agree with Sysix. We need a method to disable the additional css. There is no global YoastSEO_AMP_Frontend object that we could have used to remove the additional_css action.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
