### ISSUE TITLE
Header Color, Text Color, Post MetaColor fail to display as expected

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#44]
### What did you expect to happen?
When colors were selected for Header, Text, and PostMeta they would display.
### What happened instead?
The colors did not change. 
### How can we reproduce this behavior?
**1.Create Post**

**2.Add Colors in the Glue Plugin**

![screen shot 2016-11-14 at 1 33 10 pm](https://cloud.githubusercontent.com/assets/8238074/20277552/073da91a-aa6f-11e6-8371-8da84c8a0eff.png)

**3.See them fail to change**

![screen_shot_2016-11-14_at_1_33_25_pm](https://cloud.githubusercontent.com/assets/8238074/20277556/0ad68380-aa6f-11e6-866e-738f83b27534.png)

### Technical info
* WordPress version: 4.6.1
* Yoast SEO version: 3.8
* Yoast SEO Glue version: 0.3.3
* AMP plugin version: 0.4.2

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 159189 when this conversation has been closed.

**Comment by namaserajesh** [comment]
Same for me, I have added the colors and logo in Yoast AMP Design settings still no change.

URL: https://www.techlila.com/increase-internet-speed/amp/

Please check the screenshot:

![ss](https://cloud.githubusercontent.com/assets/1036445/21981476/9f93c26a-dc0d-11e6-8b3d-3897549eec2a.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 188919 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
