### ISSUE TITLE
[Feature Request] Provide ability to remove CSS that Yoast Glue for AMP outputs

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#45]
Certain CSS styles that the Glue for AMP uses may override other stylization. For example, the link text and hover colors may override all other customizations as "!important" is not allowed with AMP.

![screen_shot_2016-12-07_at_2_49_46_pm](https://cloud.githubusercontent.com/assets/8238074/20983977/7ac80568-bc8c-11e6-9fab-0d790d48dc95.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 163659 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
