### ISSUE TITLE
Provide support for new Google Tag Manager for AMP

### ISSUE THREAD

**Issue by guajars** [Yoast/yoastseo-amp#47]
Hi. I just found out this new implementation of GTM for AMP.

> Paste this at the end of the <head> tag in your AMP page, but only if missing and only once.
> `<!-- AMP Analytics --><script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>`
> 
> Paste this at the beginning of the <body> tag.
> `
> <amp-analytics config="https://www.googletagmanager.com/amp.json?id=GTM-XXXXXXX&gtm.url=SOURCE_URL" data-credentials="include"></amp-analytics>`

An I just could not apply to my website using Glue.

Please give support for GTM too.

Thanks.
![gtm-amp](https://cloud.githubusercontent.com/assets/12747613/21523013/2a0d2f6e-cce9-11e6-9f2d-f6239e00543b.png)

**Comment by guajars** [comment]
I feel dumb.

**Comment by koconder** [comment]
Hi @guajars im working on releasing AMP GTM support via the widely used and supported plugin for Wordpress, this is still in final stages and should be available soon, see PR here: https://github.com/duracelltomi/gtm4wp/pull/63

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
