### ISSUE TITLE
No logo in the Schema

### ISSUE THREAD

**Issue by iamazik** [Yoast/yoastseo-amp#48]
### What did you expect to happen?
The logo would appear in the Schema while on the AMP posts.

### What happened instead?
The logo doesn't appear in the Schema while on the AMP posts and Google structured data shows error `logo: A value for logo field is required`. But, non-AMP posts the `logo` value correctly in the Schema and shows no error.

### How can we reproduce this behavior?

- Setup AMP and Yoast AMP Glue plugin
- Make sure you've added the AMP icon from the Glue plugin and added the company info
- Run any AMP posts to the Google structured data tool
- You should see an error related to the `logo`

### Screenshot
![screen shot 2017 01 08 at 12 45 50 am](https://cloud.githubusercontent.com/assets/8946603/21744234/e592f8b8-d53b-11e6-8384-94cc87364090.png)

### Technical info
* WordPress version: 4.7
* Yoast SEO Premium version: 4.0.2
* Yoast SEO Glue version: 0.3.3
* AMP plugin version: 0.4.2

**Comment by ikud-s** [comment]
Hi!

Do you have found a solution for this problem? Please let me know.

regards,
Alex

**Comment by iamazik** [comment]
Please inform the customer of conversation # 207269 when this conversation has been closed.

**Comment by ikud-s** [comment]
Hi Mazedul,

did you find a solution fort he problem?

Regards
Alex


Von: Md Mazedul Islam Khan [mailto:notifications@github.com]
Gesendet: Sonntag, 9. Juli 2017 18:09
An: Yoast/yoastseo-amp <yoastseo-amp@noreply.github.com>
Cc: ikud-s <pr@ikud-seminare.de>; Comment <comment@noreply.github.com>
Betreff: Re: [Yoast/yoastseo-amp] No logo in the Schema (#48)


Please inform the customer of conversation # 207269 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 255847 when this conversation has been closed.

**Comment by ikud-s** [comment]
Problem has been solved, thank you

Von: Angi [mailto:notifications@github.com]
Gesendet: Mittwoch, 8. November 2017 03:05
An: Yoast/yoastseo-amp <yoastseo-amp@noreply.github.com>
Cc: ikud-s <pr@ikud-seminare.de>; Comment <comment@noreply.github.com>
Betreff: Re: [Yoast/yoastseo-amp] No logo in the Schema (#48)


Please inform the customer of conversation # 255847 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 297086 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 302749 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/yoastseo-amp/issues/99

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 481055 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
