### ISSUE TITLE
[Feature Request] Provide ability to add sections for advertisements

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#49]
We should consider adding the ability of the plugin for users to display advertisements on their AMP pages. For example, users could use our Glue plugin to create a special advertisement section that can then display an advertisement.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 171910 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
