### ISSUE TITLE
Setting for post type "menu" is never saved

### ISSUE THREAD

**Issue by mundschenk-at** [Yoast/yoastseo-amp#5]
The slider for the post type "menu" is never actually saved, resulting in an error notice with WP_DEBUG enabled.

> Undefined index: post_types-menu-amp in [...]/glue-for-yoast-seo-amp/classes/class-frontend.php on line 113

**Comment by jdevalk** [comment]
We shouldn't be throwing that notice on the frontend, so will be fixing that. Unsure why it's not saving though.
