### ISSUE TITLE
[Feature Request] Adjust AMP Icon suggested pixel height and width to conform with Google recommendations

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#51]
**For images, we suggest it must be at least 32px by 32px.**

![screen shot 2017-02-13 at 1 10 58 pm](https://cloud.githubusercontent.com/assets/8238074/22896452/1cbdadbe-f1ee-11e6-8403-e6fdff3f9858.png)

**However, Google suggests different recommendations**

https://developers.google.com/search/docs/data-types/articles#logo-guidelines

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
