### ISSUE TITLE
AMP plugin doesn't appear on SEO menu

### ISSUE THREAD

**Issue by KADIROSS** [Yoast/yoastseo-amp#52]
### What did you expect to happen?
After installing and activating the AMP plugin, i don't see it on WP back-office

### Technical info
* WordPress version: 4.7.2
* Yoast SEO version: 4.3 
* Yoast SEO Glue version:0.3.3
* AMP plugin version: didn't install it

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
