### ISSUE TITLE
Add notifications about dependencies

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoastseo-amp#53]
We are depending on the `Automattic AMP plugin` and `WordPress SEO` free or premium.
The plugin is not doing anything if either of these plugins is not installed.

We should throw messages for each missing plugin.

This also means that we need to add our own text-domain properly.

**Comment by jrfnl** [comment]
FYI: the text-domain part of this issue will be fixed in the very near future by an upcoming PR.
