### ISSUE TITLE
[Feature Request] Provide a check to make sure a user has installed the AMP plugin.

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#55]
We should provide a check to make sure a user has installed the AMP plugin:https://wordpress.org/plugins/amp/.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 190310 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
