### ISSUE TITLE
AMP page's JSON+LD markup does not match non-AMP pages

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#56]
### What did you expect to happen?
I expect the same JSON/LD markup to appear on the AMP Page
### What happened instead?
It did not
### How can we reproduce this behavior?
**1.Create a post**

**2.View Post's JSON/LD data**

![1](https://cloud.githubusercontent.com/assets/8238074/25049005/8370117a-210d-11e7-991b-5183875b70c0.png)

**3.View AMP posts JSON/LD Data and see that it does not match. Shows as @type Article**

![2](https://cloud.githubusercontent.com/assets/8238074/25049027/a6ace2a8-210d-11e7-8ad2-d107c739c2b6.png)

**4.Deactivate the Glue Plugin and see right JSON/LD data appear on AMP page**

![3](https://cloud.githubusercontent.com/assets/8238074/25049055/c6eac8c8-210d-11e7-982d-f1d7ad3e347d.png)

### Technical info
* WordPress version: 4.7.3
* Yoast SEO version: 4.6
* Yoast SEO Glue version: 0.4.2
* AMP plugin version: 0.4.2

However, a possible work around would be to go to the Glue for AMP plugin folder, looking for the file name "class-frontend.php", going down to line 197 and replace

`​$metadata['@type'] = $this->get_post_schema_type( $post );​
`
​With​
​
`​/**$metadata['@type'] = $this->get_post_schema_type( $post );**/`

**It appears the right JSON/LD data then appears**
![5](https://cloud.githubusercontent.com/assets/8238074/25049523/3a26224a-2110-11e7-87c8-83e770ad91dd.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 190795 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Issue also happens with @type recipe such as from a recipe plugin like: http://www.easyrecipeplugin.com/. The recipe schema does not appear on the AMP page.

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 433415 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Yoast has added new structured data to pages and the Glue Plugin is not outputting it

**Page With Structured Data**

<img width="1339" alt="Screen Shot 2019-05-03 at 10 06 38 AM" src="https://user-images.githubusercontent.com/8238074/57142685-2d55f300-6d8b-11e9-8b6f-82f2248c48e9.png">


**AMP Page Does Not Show the Right Structured Data.** 
<img width="1236" alt="Screen Shot 2019-05-03 at 10 07 51 AM" src="https://user-images.githubusercontent.com/8238074/57142745-52e2fc80-6d8b-11e9-9793-a996986c1d86.png">


**Note, that this data appearing is coming from AMP rather than Yoast or Glue**

_1.Disable Yoast and Glue_

<img width="492" alt="Screen Shot 2019-05-03 at 10 08 31 AM" src="https://user-images.githubusercontent.com/8238074/57142784-6aba8080-6d8b-11e9-832e-2510730eeed2.png">

_2 Data that appears comes from AMP_

<img width="1241" alt="Screen Shot 2019-05-03 at 10 08 50 AM" src="https://user-images.githubusercontent.com/8238074/57142810-79a13300-6d8b-11e9-9797-f01e656bcca6.png">

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 500690 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
