### ISSUE TITLE
Adding the ability to turn on/off AMP on per-post basis; off by default

### ISSUE THREAD

**Issue by kokasaurus** [Yoast/yoastseo-amp#58]
### What did you expect to happen?
My site has over 1,500 posts at this point of time, and I'd like a feature to disable AMP on all posts, but offer a switch for each of post to manually control it.
For example, my site has a mix of product reviews, editorials, guides, and news. For the past 1,500 posts, I'd like to have it just stay non-AMP. I'd like certain news posts to have AMP turned on and some off, reviews to have no AMP at all, and editorials/guides to have no AMP too.

Also, it'll be great if this there is an option on Glue to set it to default on or off on new posts. Personally, I prefer it to be defaulted to off on new posts, but that's my preference.

### What happened instead?
Everything is turned on or turned off. There is no granular control.

### How can we reproduce this behavior?
Just turn it on or off on Yoast SEO Glue

### Technical info
* WordPress version: 4.7.4
* Yoast SEO version: 4.7.1
* Yoast SEO Glue version: 0.4.2
* AMP plugin version: 0.9.48

[I asked this question on Yoast's twitter, and I was redirected here.](https://twitter.com/KokiYaps/status/861369989650980864)

Thanks a bunch!

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
