### ISSUE TITLE
Yoast Breadcrumbs causes AMP validation error

### ISSUE THREAD

**Issue by seanford** [Yoast/yoastseo-amp#60]
### What did you expect to happen?
Page should validate properly.

### What happened instead?
The attribute 'xmlns:v' may not appear in tag 'span'.

### How can we reproduce this behavior?
Add Breadcrumbs to any page using shortcode.  Breadcrumbs are still displayed on page, but AMP validation catches error described above.

This happens with or without the Yoast Glue for AMP plugin installed.

### Technical info
* WordPress version:  4.8.1 
* Yoast SEO version:  5.2 Premium
* Yoast SEO Glue version:  0.4.2
* AMP plugin version:  0.9.58.1

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
