### ISSUE TITLE
Not a valid AMP page Invalid AMP pages will not have AMP-specific features in Google search results

### ISSUE THREAD

**Issue by jerrylee** [Yoast/yoastseo-amp#61]
### Technical info
* WordPress version: 4.8.1
* Yoast SEO version: 5.3.3
* Yoast SEO Glue version: 0.4.2
* AMP plugin version: 0.5.1

Message:
Prohibited or invalid use of HTML Tag
AMP markup missing or incorrect
Invalid layout property found in AMP tag

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
