### ISSUE TITLE
AMP page not validated with google AMP-test

### ISSUE THREAD

**Issue by luchtzak** [Yoast/yoastseo-amp#62]
### What did you expect to happen?

no errors

### What happened instead?

yes erros

### How can we reproduce this behavior?

Run this via google AMP-test 

http://www.aviation24.be/airlines/condor-flugdienst/sex-scandal-german-airline-condor-pilots-sharing-videos-pictures-flight-attendants/amp/#development=1

### Technical info
* WordPress version: 4.8.1
* Yoast SEO version: 5.4 (premium)
* Yoast SEO Glue version: 0.4.2
* AMP plugin version: 0.5.1

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
