### ISSUE TITLE
[Feature Request] Provide support for Google AMP Client ID API

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#63]
Google has the Google AMP Client ID API here: https://support.google.com/analytics/answer/7486764?hl=en

We should consider providing support for it as the plugin does include a field for a Google Analytics script

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
