### ISSUE TITLE
[Feature Request] Provide ability to output other @type schemas

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#64]
The plugin will only output the @type article.

![screen shot 2017-11-27 at 2 47 20 pm](https://user-images.githubusercontent.com/8238074/33285987-068f969e-d382-11e7-9b0d-ddb1f05f7053.png)

We should consider permitting users to select other kinds of schema to output.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 268267 when this conversation has been closed.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
