### ISSUE TITLE
Two analytics snippets, textarea gets blank

### ISSUE THREAD

**Issue by DrLightman** [Yoast/yoastseo-amp#65]
### What did you expect to happen?

Put to analytics snippets, like these, to track with two different accounts:

```html
<amp-analytics type="googleanalytics" id="analytics1">
<script type="application/json">
{
  "vars": {
    "account": "UA-FIRST-ACCOUNT"
  },
  "triggers": {
    "trackPageview": {
      "on": "visible",
      "request": "pageview"
    }
  }
}
</script>
</amp-analytics>
<amp-analytics type="googleanalytics" id="analytics2">
<script type="application/json">
{
  "vars": {
    "account": "UA-SECOND-ACCOUNT"
  },
  "triggers": {
    "trackPageview": {
      "on": "visible",
      "request": "pageview"
    }
  }
}
</script>
</amp-analytics>
```

### What happened instead?

Upon saving, textarea gets blank.

### How can we reproduce this behavior?

Put that code above in the textarea and submit the form to save changes.

### Technical info
* WordPress version: 4.6.9
* Yoast SEO version: 4.8
* Yoast SEO Glue version: 0.4.2
* AMP plugin version: 0.4.2

**Comment by DrLightman** [comment]
Tried another similare version, with the triggers, but textarea gets blanked in this case too:

```html
<amp-analytics type="googleanalytics" id="analytics1">
<script type="application/json">
{
    "triggers": {
        "trackPageview": {
            "on": "visible",
            "request": "pageview"
            "vars": {
                "account": "UA-FIRST-ACCOUNT"
            },
        },
        "trackPageviewGlobal": {
            "on": "visible",
            "request": "pageview"
            "vars": {
                "account": "UA-SECOND-ACCOUNT"
            },
        }
    }
</script>
</amp-analytics>
```

**Comment by moorscode** [comment]
Hi @DrLightman 

We're sorry for the (very) long delay on your issue.

As the latest version of AMP for WordPress provides the functionality to add multiple Analytics tags, this is not something we are going to implement in this plugin.
