### ISSUE TITLE
Warning: count(): Parameter must be an array or an object 

### ISSUE THREAD

**Issue by laserjobs** [Yoast/yoastseo-amp#66]
### What did you expect to happen?
Not get an error

### What happened instead?
Warning: count(): Parameter must be an array or an object that implements Countable in xxxx/wp-includes/post-template.php on line 284

### How can we reproduce this behavior?
PHP 7.2
Amp Version 0.6.0
WordPress Version 4.9.2

### Technical info
* WordPress version: 4.9.2
* Yoast SEO version: 6.2
* Yoast SEO Glue version: 0.4.2
* AMP plugin version: 0.6.0

Warning: count(): Parameter must be an array or an object that implements Countable in xxxx/wp-includes/post-template.php on line 284

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
