### ISSUE TITLE
The text (CDATA) inside tag 'style amp-custom' contains 'CSS !important', which is disallowed.

### ISSUE THREAD

**Issue by jvmeredith** [Yoast/yoastseo-amp#67]
### What did you expect to happen?
Nothing. Just received a notification through google web console on 2/2 w/ the following message: The text (CDATA) inside tag 'style amp-custom' contains 'CSS !important', which is disallowed.

### How can we reproduce this behavior?
Here's one of our blog posts in the AMP validator:
https://validator.ampproject.org/#url=https%3A%2F%2Fwww.google.com%2Famp%2Fs%2Fblog.kettleandfire.com%2Fhow-to-drink-bone-broth%2Famp%2F

I see the following two validation messages that look to be relevant:
- The tag 'head > style[amp-boilerplate] - old variant' is deprecated - use 'head > style[amp-boilerplate]' instead.

- The mandatory text (CDATA) inside tag 'head > style[amp-boilerplate] - old variant' is missing or incorrect.

### Technical info
* WordPress version: 4.9.2
* Yoast SEO version: 6.2
* Yoast SEO Glue version: 0.4.2
* AMP plugin version: 0.6.0

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
