### ISSUE TITLE
Improve copy about what is expected in the Analytics field

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoastseo-amp#77]
We don't a lot of information about what data is expected on the Analytics input form.

We should:
- Tell what tags are expected
- Link to a page where the tag can be found (or information about generating tag)
- Have some debugging hints, making sure the quotes are correct, JSONLint validator link perhaps

**Comment by erikp** [comment]
co-signed... is there an article/instruction/example somewhere? I'm totally confused as what to enter there.

**Comment by moorscode** [comment]
The latest version of the official AMP plugin now also offers the ability to enter this information. We recommend you use that functionality instead.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
