### ISSUE TITLE
ImageObject for article empty when Glue is activated

### ISSUE THREAD

**Issue by rubenwoudsma** [Yoast/yoastseo-amp#8]
I am testing the AMP, Yoast SEO and Glue plugin on my website and noticed that the imageObject for the article is not being filled when using the Glue plugin. Looks like the code for checking/retrieving featured images is not working correctly.

Already did some small analysis. After deactivating Glue the ImageObject is filled. This surprised me as the featured image fits the requirements for AMP. 

See for example the following page: http://rubenwoudsma.nl/negenendertig/amp/#development=1

**Comment by jdevalk** [comment]
Similar to #7 

Will be fixed by #9 :)
