### ISSUE TITLE
Remove obsolete post types admin screen and page support (now supported in AMP directly)

### ISSUE THREAD

**Issue by westonruter** [Yoast/yoastseo-amp#90]
The v0.6 version of the AMP plugin added support for pages and added a UI for managing the enabled custom post types for AMP support:

![image](https://user-images.githubusercontent.com/134745/39645474-4f4a3e34-4f8d-11e8-8589-42d3f8942956.png)

This makes the post types admin screen in the Yoast plugin obsolete:

![image](https://user-images.githubusercontent.com/134745/39645462-3e87d584-4f8d-11e8-9b93-17ad50a7974d.png)

This UI should be removed in ≥0.6, as well as any built-in page support, since this is all supported in the AMP plugin directly.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
