### ISSUE TITLE
500 server error after updating to AMP 0.7.0

### ISSUE THREAD

**Issue by rmarcano** [Yoast/yoastseo-amp#91]
Updating the AMP plugin to 0.7.0 causes the following errors which prevent an AMP page from displaying:

```
Notice: AMP_Base_Sanitizer::get_body_node is deprecated since version AMP_Base_Sanitizer::$root_element! Use 0.7 instead. in /home/xxx/public_html/test/wp-includes/functions.php on line 3839

Notice: AMP_Base_Sanitizer::get_body_node is deprecated since version AMP_Base_Sanitizer::$root_element! Use 0.7 instead. in /home/xxxx/public_html/test/wp-includes/functions.php on line 3839

Fatal error: Call to a member function canonical() on null in /home/xxxx/public_html/test/wp-content/plugins/glue-for-yoast-seo-amp/classes/class-frontend.php on line 162
```
Rolling back to AMP 0.6.2 solves the issue.

### Technical info
* WordPress version: 4.9.5
* Yoast SEO version: 7.4.2
* Yoast SEO Glue version: 0.4.2
* AMP plugin version: 0.7.0

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 357569 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 357558 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 357280 when this conversation has been closed.

**Comment by JamesShaver** [comment]
Confirmed issue here, same versions.  Disabling glue plugin solves the error display issue.

**Comment by iamazik** [comment]
Fixed https://github.com/Yoast/yoastseo-amp/pull/89
