### ISSUE TITLE
Notice: AMP_Base_Sanitizer::get_body_node is deprecated since version AMP_Base_Sanitizer::$root_element! Use 0.7 instead. in /home/mysite/wp-includes/functions.php on line 3839

### ISSUE THREAD

**Issue by JamesShaver** [Yoast/yoastseo-amp#92]
### What did you expect to happen?
Navigate to AMP post, post displays
### What happened instead?
Navigate to AMP post, post displays, but includes an error in the head of the document:
Notice: AMP_Base_Sanitizer::get_body_node is deprecated since version AMP_Base_Sanitizer::$root_element! Use 0.7 instead. in /home/mysite/wp-includes/functions.php on line 3839
### How can we reproduce this behavior?
Error only displays while glue plugin is active.
### Technical info
* WordPress version: 4.9.5
* Yoast SEO version: 7.4.2
* Yoast SEO Glue version: 0.4.3
* AMP plugin version: 0.7.0

**Comment by westonruter** [comment]
The entire blacklist sanitizer class should be removed. The AMP plugin now includes a whitelist sanitizer that only allows elements and attributes which are allowed in the spec to pass through. There is no more need for blacklist sanitization.

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
