### ISSUE TITLE
Enhance compatibility with AMP for WordPress 0.7+

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoastseo-amp#95]
As AMP for WordPress has introduced a couple of features that we added because they were lacking, we should detect the version that is running and disable the implementations in our plugin.

The features now provided by the AMP plugin:
- Enable/disable AMP for post types
- Add Analytics tracking code(s)

What remains is the styling we provide for AMP pages.

**Comment by swissspidy** [comment]
> What remains is the styling we provide for AMP pages.

This is only for the legacy / classic mode though, which isn't really recommended anymore.

When not using that mode, does this plugin actually serve any purpose any more?

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
