### ISSUE TITLE
Review output escaping & data validation

### ISSUE THREAD

**Issue by jrfnl** [Yoast/yoastseo-amp#96]
There are a couple of places in the code, mostly in the `frontend.php` file where output is generated using non-standard escaping or in some cases no escaping.

A thorough review should be done for these instances and preferably a variety of unit tests should be added which try to break the existing escaping and sanitization.

Functions which need further examination:
* `YoastSEO_AMP_Frontend::additional_css()`
* `YoastSEO_AMP_Frontend::extra_head()`
* `YoastSEO_AMP_Frontend::extra_footer()`
* `YoastSEO_AMP_Options::sanitize_options()`
* `YoastSEO_AMP_Options::sanitize_analytics_json()`

**Comment by jrfnl** [comment]
When this issue is solved, the exception which is currently made for this will need to be removed from the .phpcs.xml.dist file.

https://github.com/Yoast/yoastseo-amp/blob/3e39f43a4f926113b012893069b449e14c2b7ee3/.phpcs.xml.dist#L105-L112

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
