### ISSUE TITLE
AMP Icon Fails to Override Site Logo Site Icon

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoastseo-amp#99]
### What did you expect to happen?

Entering an AMP icon in SEO-AMP-Design would override the site icon site logo

### What happened instead?

The site icon site logo stayed

### How can we reproduce this behavior?

**1.Go to Themes-Customizer-Site Identity and add in a site icon site logo**

_Image url_

![screen shot 2018-06-12 at 1 40 17 pm](https://user-images.githubusercontent.com/8238074/41307111-451ae058-6e46-11e8-83d4-7a68991b94d5.png)

_Site Icon added_

![screen shot 2018-06-12 at 1 40 31 pm](https://user-images.githubusercontent.com/8238074/41307108-43b1a90e-6e46-11e8-8882-fbe9bdf1a646.png)

**2.Go to SEO-AMP-Design and add in a logo**

![screen shot 2018-06-12 at 1 41 43 pm](https://user-images.githubusercontent.com/8238074/41307159-68ee67d4-6e46-11e8-9b77-8e1a6e11b939.png)

**3.View source code of AMP page and see that the AMP image fails to override site icon**

![screen shot 2018-06-12 at 1 44 36 pm](https://user-images.githubusercontent.com/8238074/41307290-c47da254-6e46-11e8-8450-cdea0455c1df.png)

### Technical info
* WordPress version: 4.9.6
* Yoast SEO version: 7.6.1
* Yoast SEO Glue version: 0.4.3
* AMP plugin version: 0.7.1

**Comment by Djennez** [comment]
The Glue for Yoast & AMP (yoastseo-amp) plugin is discontinued. Through collaboration with Google, all functionalities from this glue plugin have been implemented in the respective plugins. Please update the [AMP](https://wordpress.org/plugins/amp/) and [Yoast](https://wordpress.org/plugins/wordpress-seo/) plugins to the latest versions and remove the glue plugin.

This issue will be closed.
